### ISSUE TITLE
feat: support for local models (ollama)

### ISSUE THREAD

**Issue by dfosco** [callstackincubator/fabrice-ai#114]
Seeing how easy fabrice makes it to spin up a local agent CLI, it would be neat to hook it up with local models like https://github.com/ollama/ollama

I'm sure more people would like to test fabrice in a professional setting, but can't process company data on external models (i.e.: their own OpenAI API keys).

**Comment by pkarw** [comment]
Thanks, @dfosco, that's a great idea. Even now - different model providers are supported. All we need is just an implementation of the [Provider interface](https://github.com/callstackincubator/fabrice-ai/blob/main/packages/framework/src/models.ts)

Then, one can simply switch the model when defining agents. Example:

```ts
const reporter = agent({
  provider: ollama(),
  description: `
    You are skilled at preparing great looking reports.
    You can prepare a report for a patient that is about to come for a visit.
    Add info about the patient's health and symptoms.
  `,
})
```

Definitely, we need to add an example provider for Ollama + some usage examples.

**Comment by grabbou** [comment]
Yes, unfortunately, this might be tricky at the moment due to heavy reliance on OpenAI-compatible APIs. As long as the provider is OpenAI-compatible, you should be good to go.

Unfortunately, Ollama doesn't support function calling - https://ollama.com/blog/openai-compatibility. 

I would try OpenRouter, but this will not cover local use cases. 

We purposefully decided to keep this one on hold, to make sure that we don't build an unnecessary abstraction ahead of time, that would then limit us in providing some other features.

**Comment by grabbou** [comment]
To do this today, your provider should support "messages", "tools", "response_schema" and "temperature". We use these. And return compatible response. 

Once we have a working example, we may create some utility helpers for the community too!

**Comment by pkarw** [comment]
PoC - #118, there's a format with `response_format` - however it seems like ... not always :)
